POST http://localhost:8080/tarifador/tarifar
content-type: application/json

{
   "c": {
      "id": "123",
      "perros": [
         {
            "id": "124",
            "idDuenio": "456",
            "tamanio": "5"
         }
      ],
      "clarin": false,
      "laNacion": false,
      "cantidadPaseos": 5
   },
   "p": {
      "perros": [
         {
            "id": "124",
            "idDuenio": "456",
            "tamanio": "5"
         }
      ],
      "zone": "almagro",
      "paseador": {
         "id": "12345",
         "calidad": "cinco"
      },
      "tipo": "clasic"
   }
}